version: '3.8'
services:
  server:
    image: 272007598366.dkr.ecr.eu-central-1.amazonaws.com/tabsur-server:latest
    container_name: tabsur-server
    restart: unless-stopped
    privileged: true
    extra_hosts:
      - "3.249.94.227:3.249.94.227"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=3.249.94.227
      - DB_PORT=5432
      - DB_NAME=coolanu
      - DB_USER=coolanu_user
      - DB_PASSWORD=${DB_PASSWORD:-your_db_password}
      - DB_SSL=false
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-your_google_maps_key}
      - CORS_ORIGIN=https://bemyguest.dedyn.io
    ports:
      - "5000:5000"
    networks:
      - tabsur-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  client:
    image: 272007598366.dkr.ecr.eu-central-1.amazonaws.com/tabsur-client:latest
    container_name: tabsur-client
    restart: unless-stopped
    environment:
      - REACT_APP_SERVER_HOST=https://api.bemyguest.dedyn.io
      - REACT_APP_GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-your_google_maps_key}
    ports:
      - "80:80"
    depends_on:
      server:
        condition: service_healthy
    networks:
      - tabsur-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  loadbalancer:
    image: nginx:alpine
    container_name: tabsur-lb
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-https.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      server:
        condition: service_healthy
      client:
        condition: service_healthy
    networks:
      - tabsur-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  tabsur-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
