version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: tabsur-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-tabsur}
      POSTGRES_USER: ${DB_USER:-tabsur_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - tabsur-admin-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-tabsur_user} -d ${DB_NAME:-tabsur}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Node.js Backend Server
  server:
    build:
      context: .
      dockerfile: Dockerfile.server.multistage
      target: production
    container_name: tabsur-server
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: ${DB_HOST:-3.249.94.227}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-coolanu}
      DB_USER: ${DB_USER:-coolanu_user}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN:-https://localhost:3000}
      FORCE_HTTPS: "true"
    ports:
      - "5000:5000"
    depends_on: []
    networks:
      - tabsur-admin-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React Frontend Client
  client:
    build:
      context: .
      dockerfile: Dockerfile.client.multistage
      target: production
    container_name: tabsur-client
    environment:
      REACT_APP_SERVER_HOST: https://localhost:5000
      REACT_APP_GOOGLE_MAPS_API_KEY: ${REACT_APP_GOOGLE_MAPS_API_KEY}
      REACT_APP_FIREBASE_AUTH_DOMAIN: ${REACT_APP_FIREBASE_AUTH_DOMAIN}
      REACT_APP_FIREBASE_PROJECT_ID: ${REACT_APP_FIREBASE_PROJECT_ID}
      REACT_APP_FIREBASE_STORAGE_BUCKET: ${REACT_APP_FIREBASE_STORAGE_BUCKET}
      REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}
      REACT_APP_FIREBASE_APP_ID: ${REACT_APP_FIREBASE_APP_ID}
      REACT_APP_FIREBASE_MEASUREMENT_ID: ${REACT_APP_FIREBASE_MEASUREMENT_ID}
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - tabsur-admin-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Load Balancer with HTTPS
  nginx:
    image: nginx:alpine
    container_name: tabsur-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-admin-https.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - server
      - client
    networks:
      - tabsur-admin-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for Session Management (Optional)
  redis:
    image: redis:7-alpine
    container_name: tabsur-redis
    ports:
      - "6379:6379"
    networks:
      - tabsur-admin-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PgAdmin for Database Management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: tabsur-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@tabsur.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - tabsur-admin-network
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  tabsur-admin-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
