version: '3.8'

services:
  test-db:
    image: postgres:15
    container_name: test-db
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD:-}
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  test_postgres_data:
