export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";

export const SET_NOTIFICATIONS_COUNT = "SET_NOTIFICATIONS_COUNT";
export const SET_PROFILE_NOTIFICATIONS_COUNT = "SET_PROFILE_NOTIFICATIONS_COUNT";
export const SET_MESSAGES_COUNT = "SET_MESSAGES_COUNT";
export const SET_LOADING = "SET_LOADING";